site_name: PABI2 eSign
theme:
  name: material
  palette:
    primary: white
  logo: logo.png
  favicon: logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
nav:
  - Overview: index.md
  - Specs:
      - Call for Bid: specs/pd.md
      - Purchase Order: specs/po.md
      - Partner: specs/partner.md
  # - Manual:
  #     - Overview: manual/overview.md
  - Meetings:
      - 02/08/2022: meetings/02-08-2022.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
