site_name: PABI2 eSign
theme:
  name: material
  palette:
    primary: teal
  logo: logo.png
  favicon: logo.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
nav:
  - Overview: index.md
  - Specs:
      - Overview: specs/overview.md
      - Call for Bid: specs/pd.md
      - Purchase Order: specs/po.md
  - Manual:
      - Overview: manual/overview.md
  - Meetings:
      - 02/08/2022: meetings/02-08-2022.md
  - References: reference.md
